version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=napp_db
      - DB_PASSWORD=napp_db_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=stocks
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: napp_db
      POSTGRES_PASSWORD: napp_db_pass
      POSTGRES_DB: stocks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
